In [1]:
import pandas as pd
import numpy as np
import sys
from datetime import datetime

In [2]:
# import our own stuff
sys.path.append("../python/src")

from tools import read_water_data

In [3]:
# set some options
#pd.set_option('display.max_rows', 600)
#pd.set_option('display.max_columns', 600)
#pd.set_option('display.width', None)
#pd.set_option('display.max_colwidth', None)

datadir = "../data/"
cachedir = "../data/cache" 
# the projectnumber '1' cannot be used as identification
# the analyse shows, that there are multible independent projects that use that number
ignoredprojectnumbers = ['n.a.','n.a','/','aggregate',np.nan,'1']
# topX of commitment,disbursment,grantequiv,count since we cannot order the different values
topX = 200 
# only projectes that have a commitment date after the 
activedate = datetime(year=2009,month=12,day=31)

# the relevant values are
relevantvalues=['USD_Commitment_Defl','USD_Disbursement_Defl','USD_GrantEquiv']

In [4]:
%%time

# the data from oecd must be downloaded and saved as zips in the data-dir, check readme for links
oecddf = read_water_data(setname="fullset",datadir=datadir,cachedir=cachedir)

# tell me what it is
oecddf.describe()

Reading Datafrom cached file: ../data/cache/fullset.p
CPU times: user 10.6 s, sys: 3.64 s, total: 14.3 s
Wall time: 14.3 s

,USD_Commitment,USD_Disbursement,USD_Received,USD_Commitment_Defl,USD_Disbursement_Defl,USD_Received_Defl,USD_Adjustment,USD_Adjustment_Defl,USD_AmountUntied,USD_AmountPartialTied,...,TypeRepayment,NumberRepayment,Interest2,USD_Interest,USD_Outstanding,USD_Arrears_Principal,USD_Arrears_Interest,CapitalExpend,PSIflag,PSIAddType
count,3.275182e+06,3.762420e+06,2.075152e+06,3.275072e+06,3.762156e+06,2.075140e+06,60032.000000,60032.000000,1.899677e+06,1.006533e+06,...,549171.000000,564867.000000,333850.000000,1.110691e+06,881558.000000,646025.000000,651855.000000,32902.000000,3301.000000,1218.000000
mean,1.700388e+00,9.906404e-01,4.688217e-01,2.046867e+00,1.047619e+00,5.014058e-01,-0.748338,-0.839550,9.199535e-01,2.892181e-01,...,1.472700,1.854219,394.025889,1.291592e-01,6.420891,0.147550,0.218216,0.000088,1.987882,2.369458
std,2.020509e+01,1.468442e+01,7.989517e+00,2.368979e+01,1.543262e+01,8.453970e+00,11.821947,11.727234,1.252183e+01,4.405014e+00,...,1.179965,0.573195,588.434494,2.429448e+00,55.744203,2.134346,2.654434,0.001916,0.109427,0.919855
min,-1.421530e+03,-2.258730e+02,-5.030000e-01,-1.300270e+03,-2.461000e+02,-6.852520e-01,-1995.000000,-1870.620000,-1.421530e+03,-1.787180e+00,...,0.000000,0.000000,-820.000000,-3.491230e+01,-0.507119,-3.033060,-0.149653,0.000000,1.000000,1.000000
25%,0.000000e+00,3.647640e-03,0.000000e+00,0.000000e+00,3.775977e-03,0.000000e+00,-0.080000,-0.083995,0.000000e+00,0.000000e+00,...,1.000000,2.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000
50%,2.121690e-02,4.067340e-02,0.000000e+00,2.279000e-02,4.295905e-02,-0.000000e+00,-0.009426,-0.009881,4.364590e-03,0.000000e+00,...,1.000000,2.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,2.000000,3.000000
75%,1.973465e-01,2.353720e-01,-0.000000e+00,2.188643e-01,2.491832e-01,-0.000000e+00,-0.000870,-0.000894,1.250000e-01,0.000000e+00,...,1.000000,2.000000,750.000000,2.581010e-02,0.848039,0.000000,0.000000,0.000000,2.000000,3.000000
max,6.585080e+03,7.188450e+03,3.690330e+03,7.209450e+03,7.209450e+03,3.637680e+03,0.004700,0.004720,4.087360e+03,8.751230e+02,...,5.000000,52.000000,20000.000000,1.460130e+03,24053.000000,276.494000,900.342000,0.100000,2.000000,3.000000

In [5]:
## show what amount of projects we ignored in general
tmp = oecddf[oecddf['ProjectNumber'].isin(ignoredprojectnumbers)]
display(tmp.describe())

,USD_Commitment,USD_Disbursement,USD_Received,USD_Commitment_Defl,USD_Disbursement_Defl,USD_Received_Defl,USD_Adjustment,USD_Adjustment_Defl,USD_AmountUntied,USD_AmountPartialTied,...,TypeRepayment,NumberRepayment,Interest2,USD_Interest,USD_Outstanding,USD_Arrears_Principal,USD_Arrears_Interest,CapitalExpend,PSIflag,PSIAddType
count,506164.000000,696218.000000,324079.000000,506054.000000,695954.000000,324067.000000,279.000000,279.000000,149614.000000,87082.000000,...,95433.000000,95342.000000,11023.000000,201330.000000,219073.000000,182810.000000,183627.000000,828.0,313.0,5.0
mean,3.072497,1.270124,1.102845,4.765047,1.431339,1.243487,-12.928536,-12.993716,1.908869,1.600567,...,1.228160,1.904428,879.874263,0.344778,11.085768,0.304785,0.369481,0.0,2.0,1.0
std,30.962445,23.035383,18.205641,41.182705,24.445234,19.361579,59.960350,61.516836,26.188490,10.180508,...,0.903371,0.313112,1101.493216,5.254545,71.697608,2.874370,3.786326,0.0,0.0,0.0
min,-1421.530000,-109.955000,-0.503000,-1300.270000,-85.319900,-0.685252,-765.207000,-798.612000,-1421.530000,0.000000,...,1.000000,1.000000,0.000000,-25.536500,-0.005000,-3.033060,-0.031000,0.0,2.0,1.0
25%,0.008490,0.001605,-0.000000,0.008766,0.001674,-0.000000,-1.435715,-1.289290,0.004171,0.000000,...,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,2.0,1.0
50%,0.050405,0.019886,0.000000,0.057090,0.021417,0.000000,-0.084498,-0.074509,0.037882,0.000000,...,1.000000,2.000000,0.000000,0.007435,0.560340,0.000000,0.000000,0.0,2.0,1.0
75%,0.372439,0.148411,0.033058,0.487070,0.166538,0.044504,-0.003133,-0.002899,0.284813,0.329133,...,1.000000,2.000000,2000.000000,0.148691,6.474950,0.000000,0.000000,0.0,2.0,1.0
max,4138.840000,7188.450000,3690.330000,4446.860000,6310.160000,3637.680000,0.000000,0.000000,2569.920000,806.000000,...,5.000000,12.000000,9250.000000,1460.130000,10785.400000,276.494000,900.342000,0.0,2.0,1.0

In [6]:
%%time
# related to oda grant, germany and waterprojects

# filter for flowcodes ODA Grants
#tmp = tmp[tmp['FlowName'].isin(['ODA Grants'])]
# filter for elements with values
tmp = tmp[tmp[relevantvalues].any(axis = 1)]
# filter for water sector
tmp = tmp[tmp['SectorCode']=='140']
# only projects related to germany as donor
tmp = tmp[tmp['DonorCode'] == "5"]
# only projects since 2010
tmp = tmp[tmp["CommitmentDate"] > datetime(year=2002,month=12,day=31)]

display(tmp.describe())
# what do we loss in total
display(pd.DataFrame(tmp[relevantvalues].sum()))

,USD_Commitment,USD_Disbursement,USD_Received,USD_Commitment_Defl,USD_Disbursement_Defl,USD_Received_Defl,USD_Adjustment,USD_Adjustment_Defl,USD_AmountUntied,USD_AmountPartialTied,...,TypeRepayment,NumberRepayment,Interest2,USD_Interest,USD_Outstanding,USD_Arrears_Principal,USD_Arrears_Interest,CapitalExpend,PSIflag,PSIAddType
count,115.000000,111.000000,92.0,115.000000,111.000000,92.0,0.0,0.0,94.000000,0.0,...,0.0,0.0,0.0,67.0,67.0,49.0,49.0,17.0,0.0,0.0
mean,0.115691,0.076502,0.0,0.131514,0.085868,0.0,NaN,NaN,0.010763,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN
std,0.246201,0.132119,0.0,0.292825,0.159240,0.0,NaN,NaN,0.026314,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN
min,0.000000,0.000000,0.0,0.000000,0.000000,0.0,NaN,NaN,0.000000,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN
25%,0.005546,0.006835,-0.0,0.006077,0.006599,-0.0,NaN,NaN,0.000000,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN
50%,0.019915,0.026315,0.0,0.020238,0.025057,0.0,NaN,NaN,0.000000,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN
75%,0.097351,0.088346,0.0,0.110116,0.095579,0.0,NaN,NaN,0.006633,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN
max,1.914460,0.971608,0.0,2.413850,1.225050,0.0,NaN,NaN,0.154816,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN

                               0
USD_Commitment_Defl    15.124136
USD_Disbursement_Defl   9.531378
USD_GrantEquiv          4.474364

CPU times: user 610 ms, sys: 93.7 ms, total: 704 ms
Wall time: 703 ms

In [7]:
# aggregate over german water projects and group
tmp = tmp.groupby(['ProjectTitle','DonorName','SectorName','PurposeName',
             'RecipientName',pd.Grouper(key="CommitmentDate",freq="y")
             
             
             ]).agg({
    "USD_Disbursement_Defl": np.sum,
    "USD_Commitment_Defl": np.sum,
    "USD_GrantEquiv": np.sum,
    "CommitmentDate": pd.Series.count,
    "AgencyName": lambda x: "; ".join(list(set(list(map(str,x))))), # concatinate involved agencys
    "ShortDescription": lambda x: "; ".join(list(set(list(map(str,x))))), # concat short descriptions
    "LongDescription": lambda x: "; ".join(list(set(list(map(str,x))))), # concatinate long descriptions
    'CrsID': lambda x: "; ".join(list(set(list(map(str,x))))) # concatinate involved CrsIDs
})
tmp.rename(columns={"CommitmentDate": "Elements"},inplace=True)
display(tmp)

                                                                                                                                                                             USD_Disbursement_Defl  \
ProjectTitle                                       DonorName SectorName                     PurposeName                                        RecipientName CommitmentDate
AUS- UND WEITERBILDUNG VON FACH- UND FÜHRUNGSKR... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Egypt         2005-12-31                   0.002470
                                                                                                                                               Thailand      2005-12-31                   0.000000
BIWAC - Strenghtening of regional water supplie... Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... Lebanon       2017-12-31                   0.016080
                                                                                            Water sector policy and administrative management  Kenya         2017-12-31                   0.107828
                                                                                                                                               Tunisia       2017-12-31                   0.106796
...                                                                                                                                                                                            ...
slaughterhouse project waste and sewage León       Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2015-12-31                   0.005648
support of children and youth, who collect garbage Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2014-12-31                   0.020238
training program to socially integrate non-orga... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Cambodia      2010-12-31                   0.009061
water supply akeri vocational center (Meru-Diöz... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31                   0.006993
water supply in Nyere Combra Youth Eco-village ... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31                   0.013974

                                                                                                                                                                             USD_Commitment_Defl  \
ProjectTitle                                       DonorName SectorName                     PurposeName                                        RecipientName CommitmentDate
AUS- UND WEITERBILDUNG VON FACH- UND FÜHRUNGSKR... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Egypt         2005-12-31                 0.002470
                                                                                                                                               Thailand      2005-12-31                 0.002470
BIWAC - Strenghtening of regional water supplie... Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... Lebanon       2017-12-31                 0.000000
                                                                                            Water sector policy and administrative management  Kenya         2017-12-31                 0.151343
                                                                                                                                               Tunisia       2017-12-31                 0.129718
...                                                                                                                                                                                          ...
slaughterhouse project waste and sewage León       Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2015-12-31                 0.005648
support of children and youth, who collect garbage Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2014-12-31                 0.020238
training program to socially integrate non-orga... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Cambodia      2010-12-31                 0.009061
water supply akeri vocational center (Meru-Diöz... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31                 0.006993
water supply in Nyere Combra Youth Eco-village ... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31                 0.013974

                                                                                                                                                                             USD_GrantEquiv  \
ProjectTitle                                       DonorName SectorName                     PurposeName                                        RecipientName CommitmentDate
AUS- UND WEITERBILDUNG VON FACH- UND FÜHRUNGSKR... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Egypt         2005-12-31            0.000000
                                                                                                                                               Thailand      2005-12-31            0.000000
BIWAC - Strenghtening of regional water supplie... Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... Lebanon       2017-12-31            0.016080
                                                                                            Water sector policy and administrative management  Kenya         2017-12-31            0.101454
                                                                                                                                               Tunisia       2017-12-31            0.101839
...                                                                                                                                                                                     ...
slaughterhouse project waste and sewage León       Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2015-12-31            0.005115
support of children and youth, who collect garbage Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2014-12-31            0.000000
training program to socially integrate non-orga... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Cambodia      2010-12-31            0.000000
water supply akeri vocational center (Meru-Diöz... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31            0.000000
water supply in Nyere Combra Youth Eco-village ... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31            0.000000

                                                                                                                                                                             Elements  \
ProjectTitle                                       DonorName SectorName                     PurposeName                                        RecipientName CommitmentDate
AUS- UND WEITERBILDUNG VON FACH- UND FÜHRUNGSKR... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Egypt         2005-12-31             1
                                                                                                                                               Thailand      2005-12-31             1
BIWAC - Strenghtening of regional water supplie... Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... Lebanon       2017-12-31             1
                                                                                            Water sector policy and administrative management  Kenya         2017-12-31             1
                                                                                                                                               Tunisia       2017-12-31             2
...                                                                                                                                                                               ...
slaughterhouse project waste and sewage León       Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2015-12-31             1
support of children and youth, who collect garbage Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2014-12-31             1
training program to socially integrate non-orga... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Cambodia      2010-12-31             1
water supply akeri vocational center (Meru-Diöz... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31             1
water supply in Nyere Combra Youth Eco-village ... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31             1

                                                                                                                                                                                                       AgencyName  \
ProjectTitle                                       DonorName SectorName                     PurposeName                                        RecipientName CommitmentDate
AUS- UND WEITERBILDUNG VON FACH- UND FÜHRUNGSKR... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Egypt         2005-12-31      Federal states and local governments
                                                                                                                                               Thailand      2005-12-31      Federal states and local governments
BIWAC - Strenghtening of regional water supplie... Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... Lebanon       2017-12-31                  Federal State of Bavaria
                                                                                            Water sector policy and administrative management  Kenya         2017-12-31                  Federal State of Bavaria
                                                                                                                                               Tunisia       2017-12-31                  Federal State of Bavaria
...                                                                                                                                                                                                           ...
slaughterhouse project waste and sewage León       Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2015-12-31                     City State of Hamburg
support of children and youth, who collect garbage Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2014-12-31                     City State of Hamburg
training program to socially integrate non-orga... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Cambodia      2010-12-31      Federal states and local governments
water supply akeri vocational center (Meru-Diöz... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31      Federal states and local governments
water supply in Nyere Combra Youth Eco-village ... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31      Federal states and local governments

                                                                                                                                                                                                              ShortDescription  \
ProjectTitle                                       DonorName SectorName                     PurposeName                                        RecipientName CommitmentDate
AUS- UND WEITERBILDUNG VON FACH- UND FÜHRUNGSKR... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Egypt         2005-12-31                              WASTE MANAGEMENT/DISPOSAL
                                                                                                                                               Thailand      2005-12-31                                       HIGHER EDUCATION
BIWAC - Strenghtening of regional water supplie... Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... Lebanon       2017-12-31      BIWAC - STRENGHTENING OF REGIONAL WATER SUPPLI...
                                                                                            Water sector policy and administrative management  Kenya         2017-12-31      BIWAC - STRENGHTENING OF REGIONAL WATER SUPPLI...
                                                                                                                                               Tunisia       2017-12-31      BIWAC - STRENGHTENING OF REGIONAL WATER SUPPLI...
...                                                                                                                                                                                                                        ...
slaughterhouse project waste and sewage León       Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2015-12-31           SLAUGHTERHOUSE PROJECT WASTE AND SEWAGE LEÓN
support of children and youth, who collect garbage Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2014-12-31      SUPPORT OF CHILDREN AND YOUTH, WHO COLLECT GAR...
training program to socially integrate non-orga... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Cambodia      2010-12-31      TRAINING PROGRAM TO SOCIALLY INTEGRATE NON-ORG...
water supply akeri vocational center (Meru-Diöz... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31                   WATER SUPPLY AKERI VOCATIONAL CENTER
water supply in Nyere Combra Youth Eco-village ... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31         WATER SUPPLY IN NYERE COMBRA YOUTH ECO-VILLAGE

                                                                                                                                                                                                               LongDescription  \
ProjectTitle                                       DonorName SectorName                     PurposeName                                        RecipientName CommitmentDate
AUS- UND WEITERBILDUNG VON FACH- UND FÜHRUNGSKR... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Egypt         2005-12-31                                                    nan
                                                                                                                                               Thailand      2005-12-31                                                    nan
BIWAC - Strenghtening of regional water supplie... Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... Lebanon       2017-12-31      Improving the knowledge of experts of the Leba...
                                                                                            Water sector policy and administrative management  Kenya         2017-12-31      BIWAC - Strenghtening of regional water suppli...
                                                                                                                                               Tunisia       2017-12-31      BIWAC - Strenghtening of regional water suppli...
...                                                                                                                                                                                                                        ...
slaughterhouse project waste and sewage León       Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2015-12-31                                    Treatment of sewage
support of children and youth, who collect garbage Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2014-12-31                      advancement of children and youth
training program to socially integrate non-orga... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Cambodia      2010-12-31      training of waste-pickers, basics of waste sep...
water supply akeri vocational center (Meru-Diöz... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31      water supply akeri vocational center (Meru-Diö...
water supply in Nyere Combra Youth Eco-village ... Germany   I.4. Water Supply & Sanitation Basic drinking water supply and basic sanitation   Tanzania      2006-12-31      water supply in Nyere Combra Youth Eco-village...

                                                                                                                                                                                              CrsID
ProjectTitle                                       DonorName SectorName                     PurposeName                                        RecipientName CommitmentDate
AUS- UND WEITERBILDUNG VON FACH- UND FÜHRUNGSKR... Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Egypt         2005-12-31                 2005004156z
                                                                                                                                               Thailand      2005-12-31                 2005001490z
BIWAC - Strenghtening of regional water supplie... Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... Lebanon       2017-12-31                  2018014171
                                                                                            Water sector policy and administrative management  Kenya         2017-12-31                  2017014470
                                                                                                                                               Tunisia       2017-12-31      2017014499; 2018014193
...                                                                                                                                                                                             ...
slaughterhouse project waste and sewage León       Germany   I.4. Water Supply & Sanitation Waste management/disposal                          Nicaragua     2015-12-31                  2015011317

In [8]:
%%time
# filter for 'n.a.'-Projects and 'aggregate'
tmp = oecddf[~oecddf['ProjectNumber'].isin(ignoredprojectnumbers)]

# filter for flowcodes ODA Grants
#tmp = tmp[tmp['FlowName'].isin(['ODA Grants'])]

# filter for elements with values
tmp = tmp[tmp[relevantvalues].any(axis = 1)]

# create a list of projects
projectlist = list(np.unique(tmp.reset_index().set_index('ProjectNumber').index))

CPU times: user 7.1 s, sys: 1.73 s, total: 8.83 s
Wall time: 8.84 s

In [9]:
%%time
# filter for projectnames
tmp = oecddf[oecddf['ProjectNumber'].isin(projectlist)]
#tmp = tmp[tmp['FlowName'].isin(['ODA Grants'])]
# only projects related to water
tmp = tmp[tmp['SectorCode']=='140']
# only projects related to germany as donor
tmp = tmp[tmp['DonorCode'] == "5"]
# only projects since 2010
tmp = tmp[tmp["CommitmentDate"] > activedate]

CPU times: user 3.3 s, sys: 369 ms, total: 3.67 s
Wall time: 3.67 s

In [10]:
%%time
# aggregate to get a list of biggest projects
# "big values" means high disbursement, commitment, 
# grantequiv or simply a high number of transactions

tmp = tmp.groupby(['ProjectNumber']).agg({"USD_Disbursement_Defl": np.sum,
                                          "USD_Commitment_Defl": np.sum,
                                          "USD_GrantEquiv": np.sum,
                                          "CommitmentDate": pd.Series.count})


a = list(tmp.reset_index().set_index('ProjectNumber').sort_values('USD_Disbursement_Defl',ascending=False).head(topX).index)
b = list(tmp.reset_index().set_index('ProjectNumber').sort_values('USD_Commitment_Defl',ascending=False).head(topX).index)
c = list(tmp.reset_index().set_index('ProjectNumber').sort_values('USD_GrantEquiv',ascending=False).head(topX).index)
d = list(tmp.reset_index().set_index('ProjectNumber').sort_values('CommitmentDate',ascending=False).head(topX).index)

topgermanwater = list(np.unique(a+b+c+d))

CPU times: user 40 ms, sys: 16 µs, total: 40 ms
Wall time: 39.3 ms

In [11]:
len(topgermanwater)

454

In [12]:
# show what we loss  
#pd.set_option('display.max_rows', 600)
#pd.set_option('display.max_columns', 600)
tmp = oecddf[~oecddf['ProjectNumber'].isin(topgermanwater)].copy()
tmp = tmp[tmp['SectorCode']=='140']
# only projects related to germany as donor
tmp = tmp[tmp['DonorCode'] == "5"]
tmp = tmp[tmp["CommitmentDate"] > activedate]
display(tmp.describe(percentiles=[0.5,0.75,0.9,0.95,0.99]))

# aggregate over german water projects and group
tmp = tmp.groupby(["AgencyName",'FlowName',
                   #'RecipientName',
                   #pd.Grouper(key="CommitmentDate",freq="y"),
                   'PurposeName'
             ]).agg({
    "USD_Disbursement_Defl": np.sum,
    "USD_Commitment_Defl": np.sum,
    "USD_GrantEquiv": np.sum,
    "CommitmentDate": pd.Series.count,
    "ProjectNumber": lambda x: len(list(set(list(map(str,x))))), # count unique ProjectNumbers
    "ProjectTitle": lambda x: len(list(set(list(map(str,x))))) # count unique ProjectNumbers
})
tmp.rename(columns={
    "CommitmentDate": "Elements",
    "ProjectNumber": "Unique ProjectNumbers",
    "ProjectTitle": "Unique ProjectTitle"
},inplace=True)

display(tmp)

,USD_Commitment,USD_Disbursement,USD_Received,USD_Commitment_Defl,USD_Disbursement_Defl,USD_Received_Defl,USD_Adjustment,USD_Adjustment_Defl,USD_AmountUntied,USD_AmountPartialTied,...,TypeRepayment,NumberRepayment,Interest2,USD_Interest,USD_Outstanding,USD_Arrears_Principal,USD_Arrears_Interest,CapitalExpend,PSIflag,PSIAddType
count,3247.000000,3247.000000,3246.000000,3247.000000,3247.000000,3246.000000,0.0,0.0,3247.000000,0.0,...,36.000000,36.0,214.0,2522.000000,2522.000000,1987.0,1987.0,618.0,1.0,1.0
mean,0.382607,0.167586,0.001485,0.391906,0.170846,0.001530,NaN,NaN,0.318722,NaN,...,1.222222,2.0,0.0,0.000160,0.017960,0.0,0.0,0.0,2.0,1.0
std,1.361679,0.380575,0.049655,1.393697,0.383063,0.051238,NaN,NaN,1.328175,NaN,...,0.929243,0.0,0.0,0.002657,0.317125,0.0,0.0,0.0,NaN,NaN
min,0.000000,0.000000,-0.000000,0.000000,0.000000,-0.000000,NaN,NaN,0.000000,NaN,...,1.000000,2.0,0.0,0.000000,0.000000,0.0,0.0,0.0,2.0,1.0
50%,0.000546,0.055013,-0.000000,0.000550,0.056575,-0.000000,NaN,NaN,0.000000,NaN,...,1.000000,2.0,0.0,0.000000,0.000000,0.0,0.0,0.0,2.0,1.0
75%,0.138871,0.141149,-0.000000,0.143269,0.144103,-0.000000,NaN,NaN,0.000000,NaN,...,1.000000,2.0,0.0,0.000000,0.000000,0.0,0.0,0.0,2.0,1.0
90%,0.653060,0.388239,-0.000000,0.659718,0.393632,-0.000000,NaN,NaN,0.465463,NaN,...,1.000000,2.0,0.0,0.000000,0.000000,0.0,0.0,0.0,2.0,1.0
95%,2.171565,0.796166,-0.000000,2.264502,0.822640,-0.000000,NaN,NaN,1.850493,NaN,...,2.000000,2.0,0.0,0.000000,0.000000,0.0,0.0,0.0,2.0,1.0
99%,7.832902,1.751272,-0.000000,8.488170,1.739096,-0.000000,NaN,NaN,7.386991,NaN,...,5.000000,2.0,0.0,0.000000,0.000000,0.0,0.0,0.0,2.0,1.0
max,14.594700,6.051340,2.238890,14.162600,6.237980,2.316060,NaN,NaN,14.594700,NaN,...,5.000000,2.0,0.0,0.072145,12.081400,0.0,0.0,0.0,2.0,1.0

                                                                                                                  USD_Disbursement_Defl  \
AgencyName                                         FlowName   PurposeName
Bundesministerium für Wirtschaftliche Zusammena... ODA Grants Basic drinking water supply                                     32.413682
                                                              Basic drinking water supply and basic sanitation                41.199843
                                                              Basic sanitation                                                34.930024
                                                              Education and training in water supply and sani...               6.008431
                                                              River basins development                                        12.120679
...                                                                                                                                 ...
Kreditanstalt für Wiederaufbau                     ODA Loans  River basins development                                         6.237980
                                                              Sanitation - large systems                                       0.366897
                                                              Waste management/disposal                                        2.956672
                                                              Water supply - large systems                                     0.000000
                                                              Water supply and sanitation - large systems                     10.705704

                                                                                                                  USD_Commitment_Defl  \
AgencyName                                         FlowName   PurposeName
Bundesministerium für Wirtschaftliche Zusammena... ODA Grants Basic drinking water supply                                   44.086840
                                                              Basic drinking water supply and basic sanitation             207.633642
                                                              Basic sanitation                                              44.341984
                                                              Education and training in water supply and sani...            11.594015
                                                              River basins development                                      31.240454
...                                                                                                                               ...
Kreditanstalt für Wiederaufbau                     ODA Loans  River basins development                                       0.000000
                                                              Sanitation - large systems                                     9.520960
                                                              Waste management/disposal                                     11.024600
                                                              Water supply - large systems                                  11.980900
                                                              Water supply and sanitation - large systems                   13.707900

                                                                                                                  USD_GrantEquiv  \
AgencyName                                         FlowName   PurposeName
Bundesministerium für Wirtschaftliche Zusammena... ODA Grants Basic drinking water supply                              23.512050
                                                              Basic drinking water supply and basic sanitation         28.228671
                                                              Basic sanitation                                         22.831682
                                                              Education and training in water supply and sani...        4.108471
                                                              River basins development                                  5.303251
...                                                                                                                          ...
Kreditanstalt für Wiederaufbau                     ODA Loans  River basins development                                  2.153360
                                                              Sanitation - large systems                                0.102447
                                                              Waste management/disposal                                 1.038468
                                                              Water supply - large systems                              0.000000
                                                              Water supply and sanitation - large systems               2.506786

                                                                                                                  Elements  \
AgencyName                                         FlowName   PurposeName
Bundesministerium für Wirtschaftliche Zusammena... ODA Grants Basic drinking water supply                              335
                                                              Basic drinking water supply and basic sanitation         232
                                                              Basic sanitation                                         107
                                                              Education and training in water supply and sani...        21
                                                              River basins development                                  24
...                                                                                                                    ...
Kreditanstalt für Wiederaufbau                     ODA Loans  River basins development                                   1
                                                              Sanitation - large systems                                 2
                                                              Waste management/disposal                                  6
                                                              Water supply - large systems                               1
                                                              Water supply and sanitation - large systems                9

                                                                                                                  Unique ProjectNumbers  \
AgencyName                                         FlowName   PurposeName
Bundesministerium für Wirtschaftliche Zusammena... ODA Grants Basic drinking water supply                                           160
                                                              Basic drinking water supply and basic sanitation                      106
                                                              Basic sanitation                                                       46
                                                              Education and training in water supply and sani...                      9
                                                              River basins development                                               10
...                                                                                                                                 ...
Kreditanstalt für Wiederaufbau                     ODA Loans  River basins development                                                1
                                                              Sanitation - large systems                                              1
                                                              Waste management/disposal                                               2
                                                              Water supply - large systems                                            1
                                                              Water supply and sanitation - large systems                             4

                                                                                                                  Unique ProjectTitle
AgencyName                                         FlowName   PurposeName
Bundesministerium für Wirtschaftliche Zusammena... ODA Grants Basic drinking water supply                                         162
                                                              Basic drinking water supply and basic sanitation                    115
                                                              Basic sanitation                                                     52
                                                              Education and training in water supply and sani...                    9
                                                              River basins development                                             14
...                                                                                                                               ...
Kreditanstalt für Wiederaufbau                     ODA Loans  River basins development                                              1
                                                              Sanitation - large systems                                            1
                                                              Waste management/disposal                                             2
                                                              Water supply - large systems                                          1
                                                              Water supply and sanitation - large systems                           4

[112 rows x 6 columns]

In [13]:
%%time

df = oecddf[oecddf['ProjectNumber'].isin(topgermanwater)].copy()
# only watersector
df = df[df['SectorCode']=='140']
# only projects related to germany as donor
df = df[df['DonorCode'] == "5"]

# aggregate over german water projects and group
df = df.groupby(['ProjectNumber','FlowName','DonorName','SectorName','PurposeName',
             'RecipientName',pd.Grouper(key="CommitmentDate",freq="y")
             
             
             ]).agg({
    "USD_Disbursement_Defl": np.sum,
    "USD_Commitment_Defl": np.sum,
    "USD_GrantEquiv": np.sum,
    "CommitmentDate": pd.Series.count,
    "AgencyName": lambda x: "; ".join(list(set(list(map(str,x))))), # concatinate involved agencys
    "ProjectTitle": lambda x: "; ".join(list(set(list(map(str,x))))), # concatinate used projecttitles
    "ShortDescription": lambda x: "; ".join(list(set(list(map(str,x))))), # concat short descriptions
    "LongDescription": lambda x: "; ".join(list(set(list(map(str,x))))), # concatinate long descriptions
    'CrsID': lambda x: "; ".join(list(set(list(map(str,x))))) # concatinate involved CrsIDs
})
# rename the feature used for counting to Elements
df.rename(columns={"CommitmentDate": "Elements"},inplace=True)
# write out
df.reset_index().to_csv("projects_by_year.csv")
display(df)

                                                                                                                                                             USD_Disbursement_Defl  \
ProjectNumber FlowName          DonorName SectorName                     PurposeName                                        RecipientName    CommitmentDate
01BEX03C13    ODA Grants        Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... India            2013-12-31                   0.346829
                                                                                                                                             2016-12-31                   0.084390
                                                                                                                                             2017-12-31                   0.068504
                                                                                                                                             2018-12-31                   0.000474
01LN1316A     ODA Grants        Germany   I.4. Water Supply & Sanitation Water resources conservation (including data co... Ghana            2014-12-31                   0.841115
...                                                                                                                                                                            ...
DEG150149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2015-12-31                  45.114700
DEG170149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2017-12-31                  29.952300
DEG180024     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Africa, regional 2018-12-31                   9.962110
PDF           ODA Grants        Germany   I.4. Water Supply & Sanitation Basic drinking water supply                        Afghanistan      2012-12-31                   0.322853
                                                                         River basins development                           Afghanistan      2012-12-31                   0.114636

                                                                                                                                                             USD_Commitment_Defl  \
ProjectNumber FlowName          DonorName SectorName                     PurposeName                                        RecipientName    CommitmentDate
01BEX03C13    ODA Grants        Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... India            2013-12-31                 0.414071
                                                                                                                                             2016-12-31                 0.027250
                                                                                                                                             2017-12-31                 0.068504
                                                                                                                                             2018-12-31                 0.000474
01LN1316A     ODA Grants        Germany   I.4. Water Supply & Sanitation Water resources conservation (including data co... Ghana            2014-12-31                 0.000000
...                                                                                                                                                                          ...
DEG150149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2015-12-31                45.114700
DEG170149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2017-12-31                29.952300
DEG180024     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Africa, regional 2018-12-31                 9.962110
PDF           ODA Grants        Germany   I.4. Water Supply & Sanitation Basic drinking water supply                        Afghanistan      2012-12-31                 0.322853
                                                                         River basins development                           Afghanistan      2012-12-31                 0.114636

                                                                                                                                                             USD_GrantEquiv  \
ProjectNumber FlowName          DonorName SectorName                     PurposeName                                        RecipientName    CommitmentDate
01BEX03C13    ODA Grants        Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... India            2013-12-31            0.120606
                                                                                                                                             2016-12-31            0.077081
                                                                                                                                             2017-12-31            0.064455
                                                                                                                                             2018-12-31            0.000474
01LN1316A     ODA Grants        Germany   I.4. Water Supply & Sanitation Water resources conservation (including data co... Ghana            2014-12-31            0.800354
...                                                                                                                                                                     ...
DEG150149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2015-12-31           40.854000
DEG170149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2017-12-31           28.181700
DEG180024     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Africa, regional 2018-12-31            9.962110
PDF           ODA Grants        Germany   I.4. Water Supply & Sanitation Basic drinking water supply                        Afghanistan      2012-12-31            0.000000
                                                                         River basins development                           Afghanistan      2012-12-31            0.000000

                                                                                                                                                             Elements  \
ProjectNumber FlowName          DonorName SectorName                     PurposeName                                        RecipientName    CommitmentDate
01BEX03C13    ODA Grants        Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... India            2013-12-31             3
                                                                                                                                             2016-12-31             1
                                                                                                                                             2017-12-31             1
                                                                                                                                             2018-12-31             1
01LN1316A     ODA Grants        Germany   I.4. Water Supply & Sanitation Water resources conservation (including data co... Ghana            2014-12-31             2
...                                                                                                                                                               ...
DEG150149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2015-12-31             1
DEG170149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2017-12-31             1
DEG180024     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Africa, regional 2018-12-31             1
PDF           ODA Grants        Germany   I.4. Water Supply & Sanitation Basic drinking water supply                        Afghanistan      2012-12-31             7
                                                                         River basins development                           Afghanistan      2012-12-31             2

                                                                                                                                                                                                    AgencyName  \
ProjectNumber FlowName          DonorName SectorName                     PurposeName                                        RecipientName    CommitmentDate
01BEX03C13    ODA Grants        Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... India            2013-12-31      Federal Ministry of Education and Research; Fe...
                                                                                                                                             2016-12-31             Federal Ministry of Education and Research
                                                                                                                                             2017-12-31             Federal Ministry of Education and Research
                                                                                                                                             2018-12-31             Federal Ministry of Education and Research
01LN1316A     ODA Grants        Germany   I.4. Water Supply & Sanitation Water resources conservation (including data co... Ghana            2014-12-31             Federal Ministry of Education and Research
...                                                                                                                                                                                                        ...
DEG150149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2015-12-31              German Investment and Development Company
DEG170149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2017-12-31              German Investment and Development Company
DEG180024     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Africa, regional 2018-12-31              German Investment and Development Company
PDF           ODA Grants        Germany   I.4. Water Supply & Sanitation Basic drinking water supply                        Afghanistan      2012-12-31                                     Federal Ministries
                                                                         River basins development                           Afghanistan      2012-12-31                                     Federal Ministries

                                                                                                                                                                                                  ProjectTitle  \
ProjectNumber FlowName          DonorName SectorName                     PurposeName                                        RecipientName    CommitmentDate
01BEX03C13    ODA Grants        Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... India            2013-12-31      Exchanges with Other Countries in the Field of...
                                                                                                                                             2016-12-31      Exchanges with Other Countries in the Field of...
                                                                                                                                             2017-12-31      Exchanges with Other Countries in the Field of...
                                                                                                                                             2018-12-31      Exchanges with Other Countries in the Field of...
01LN1316A     ODA Grants        Germany   I.4. Water Supply & Sanitation Water resources conservation (including data co... Ghana            2014-12-31                   Megacities and urban conglomerations
...                                                                                                                                                                                                        ...
DEG150149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2015-12-31                                      Equity Investment
DEG170149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2017-12-31                                      Equity Investment
DEG180024     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Africa, regional 2018-12-31                                      Equity Investment
PDF           ODA Grants        Germany   I.4. Water Supply & Sanitation Basic drinking water supply                        Afghanistan      2012-12-31      Drilling of 32 wells; Construction of a drinki...
                                                                         River basins development                           Afghanistan      2012-12-31                      Construction of a protective wall

                                                                                                                                                                                              ShortDescription  \
ProjectNumber FlowName          DonorName SectorName                     PurposeName                                        RecipientName    CommitmentDate
01BEX03C13    ODA Grants        Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... India            2013-12-31      EXCHANGES WITH OTHER COUNTRIES IN THE FIELD OF...
                                                                                                                                             2016-12-31      EXCHANGES WITH OTHER COUNTRIES IN THE FIELD OF...
                                                                                                                                             2017-12-31      EXCHANGES WITH OTHER COUNTRIES IN THE FIELD OF...
                                                                                                                                             2018-12-31      EXCHANGES WITH OTHER COUNTRIES IN THE FIELD OF...
01LN1316A     ODA Grants        Germany   I.4. Water Supply & Sanitation Water resources conservation (including data co... Ghana            2014-12-31                   MEGACITIES AND URBAN CONGLOMERATIONS
...                                                                                                                                                                                                        ...
DEG150149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2015-12-31                                      EQUITY INVESTMENT
DEG170149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2017-12-31                                      EQUITY INVESTMENT
DEG180024     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Africa, regional 2018-12-31                                      EQUITY INVESTMENT
PDF           ODA Grants        Germany   I.4. Water Supply & Sanitation Basic drinking water supply                        Afghanistan      2012-12-31      CONSTRUCTION OF A DRINKING WATER SYSTEM; DRILL...
                                                                         River basins development                           Afghanistan      2012-12-31                      CONSTRUCTION OF A PROTECTIVE WALL

                                                                                                                                                                                               LongDescription  \
ProjectNumber FlowName          DonorName SectorName                     PurposeName                                        RecipientName    CommitmentDate
01BEX03C13    ODA Grants        Germany   I.4. Water Supply & Sanitation Education and training in water supply and sani... India            2013-12-31      Collaborative project - Exporting vocational t...
                                                                                                                                             2016-12-31      Collaborative project - Exporting vocational t...
                                                                                                                                             2017-12-31      Collaborative project - Exporting vocational t...
                                                                                                                                             2018-12-31      Collaborative project - Exporting vocational t...
01LN1316A     ODA Grants        Germany   I.4. Water Supply & Sanitation Water resources conservation (including data co... Ghana            2014-12-31      WaterPower - Collision of Mega-Trends in a Wes...
...                                                                                                                                                                                                        ...
DEG150149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2015-12-31                                  Waste water treatment
DEG170149     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Asia, regional   2017-12-31                            Water supply and sanitation
DEG180024     Equity Investment Germany   I.4. Water Supply & Sanitation Water supply and sanitation - large systems        Africa, regional 2018-12-31                    Water supply, waste water treatment
PDF           ODA Grants        Germany   I.4. Water Supply & Sanitation Basic drinking water supply                        Afghanistan      2012-12-31      Drilling of a well; Construction of a drinking...
                                                                         River basins development                           Afghanistan      2012-12-31                      Construction of a protective wall

                                                                                                                                                                                                         CrsID
ProjectNumber FlowName          DonorName SectorName                     PurposeName                                        RecipientName    CommitmentDate

CPU times: user 168 ms, sys: 457 µs, total: 168 ms
Wall time: 167 ms

In [14]:
%%time

df = oecddf[oecddf['ProjectNumber'].isin(topgermanwater)].copy()
# only watersector
df = df[df['SectorCode']=='140']
# only projects related to germany as donor
df = df[df['DonorCode'] == "5"]
df['minCommitDate'] = df['CommitmentDate']
df['maxCommitDate'] = df['CommitmentDate']
df['maxExpectedStartDate'] = df['ExpectedStartDate']
df['minExpectedStartDate'] = df['ExpectedStartDate']
df['maxCompletionDate'] = df['CompletionDate']
df['minCompletionDate'] = df['CompletionDate']
df['minRepaydate1'] = df['Repaydate1']
df['maxRepaydate1'] = df['Repaydate1']
df['minRepaydate2'] = df['Repaydate2']
df['maxRepaydate2'] = df['Repaydate2']
df['minYear'] = df['Year']
df['maxYear'] = df['Year']


# aggregate over german water projects and group
df = df.groupby(['ProjectNumber','FlowName','DonorName','SectorName','PurposeName',
             'RecipientName'
             ]).agg({
    "USD_Disbursement_Defl": np.sum,
    "USD_Commitment_Defl": np.sum,
    "USD_GrantEquiv": np.sum,
    "CommitmentDate": pd.Series.count,
    "AgencyName": lambda x: "; ".join(list(set(list(map(str,x))))), # concatinate involved agencys
    "ProjectTitle": lambda x: "; ".join(list(set(list(map(str,x))))), # concatinate used projecttitles
    "ShortDescription": lambda x: "; ".join(list(set(list(map(str,x))))), # concat short descriptions
    "LongDescription": lambda x: "; ".join(list(set(list(map(str,x))))), # concatinate long descriptions
    'CrsID': lambda x: "; ".join(list(set(list(map(str,x))))), # concatinate involved CrsIDs
    'minCommitDate': np.min,
    'maxCommitDate': np.max,
    'minYear': np.min,
    'maxYear': np.max,
    'maxExpectedStartDate': np.max,
    'minExpectedStartDate': np.min,
    'maxCompletionDate': np.max,
    'minCompletionDate': np.min,
    'minRepaydate1': np.min,
    'maxRepaydate1': np.max,
    'minRepaydate2': np.min,
    'maxRepaydate2': np.max
    
})
# rename the feature used for counting to Elements
df.rename(columns={"CommitmentDate": "Elements"},inplace=True)
# write out
df = df.reset_index()
#df['durration in days'] = df['maxCommitDate'] - df['minCommitDate']
#df['durration in days'] = df['durration in days'].apply(lambda x: x.days)
#df['durration in years'] = df['durration in days']/364.25
#df['USD_Disbursement_Defl per year'] = df['USD_Disbursement_Defl'] / df['durration in years']
#df['USD_Commitment_Defl per year'] = df['USD_Commitment_Defl'] / df['durration in years']
#df['USD_GrantEquiv per year'] = df['USD_GrantEquiv'] / df['durration in years']
df.to_csv('projects_with_durration.csv')
display(df)

,ProjectNumber,FlowName,DonorName,SectorName,PurposeName,RecipientName,USD_Disbursement_Defl,USD_Commitment_Defl,USD_GrantEquiv,Elements,...,minYear,maxYear,maxExpectedStartDate,minExpectedStartDate,maxCompletionDate,minCompletionDate,minRepaydate1,maxRepaydate1,minRepaydate2,maxRepaydate2
0,01BEX03C13,ODA Grants,Germany,I.4. Water Supply & Sanitation,Education and training in water supply and san...,India,0.500197,0.510299,0.262616,6,...,2013,2018,2013-06-01,2013-06-01,2017-05-31,2016-05-31,NaT,NaT,NaT,NaT
1,01LN1316A,ODA Grants,Germany,I.4. Water Supply & Sanitation,Water resources conservation (including data c...,Ghana,1.287255,0.035407,1.246494,3,...,2017,2019,2014-04-01,2014-04-01,2020-04-30,2018-09-30,NaT,NaT,NaT,NaT
2,01LN1316A,ODA Grants,Germany,I.4. Water Supply & Sanitation,Water resources conservation (including data c...,"South of Sahara, regional",0.827983,1.789830,0.531645,3,...,2014,2016,2014-04-01,2014-04-01,2018-03-31,2018-03-31,NaT,NaT,NaT,NaT
3,02WCL1217E,ODA Grants,Germany,I.4. Water Supply & Sanitation,Water resources conservation (including data c...,Viet Nam,0.318466,0.329089,0.074206,5,...,2012,2016,2012-07-01,2012-07-01,2015-10-31,2015-06-30,NaT,NaT,NaT,NaT
4,02WCL1217F,ODA Grants,Germany,I.4. Water Supply & Sanitation,Water resources conservation (including data c...,Viet Nam,0.057181,0.059508,0.022695,5,...,2012,2016,2012-08-01,2012-08-01,2015-10-31,2015-07-31,NaT,NaT,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,DEG150149,Equity Investment,Germany,I.4. Water Supply & Sanitation,Water supply and sanitation - large systems,"Asia, regional",45.114700,45.114700,40.854000,1,...,2015,2015,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
494,DEG170149,Equity Investment,Germany,I.4. Water Supply & Sanitation,Water supply and sanitation - large systems,"Asia, regional",29.952300,29.952300,28.181700,1,...,2017,2017,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
495,DEG180024,Equity Investment,Germany,I.4. Water Supply & Sanitation,Water supply and sanitation - large systems,"Africa, regional",9.962110,9.962110,9.962110,1,...,2018,2018,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
496,PDF,ODA Grants,Germany,I.4. Water Supply & Sanitation,Basic drinking water supply,Afghanistan,0.322853,0.322853,0.000000,7,...,2012,2012,2012-01-01,2012-01-01,2012-12-31,2012-12-31,NaT,NaT,NaT,NaT
497,PDF,ODA Grants,Germany,I.4. Water Supply & Sanitation,River basins development,Afghanistan,0.114636,0.114636,0.000000,2,...,2012,2012,2012-01-01,2012-01-01,2012-12-31,2012-12-31,NaT,NaT,NaT,NaT

CPU times: user 221 ms, sys: 238 µs, total: 221 ms
Wall time: 220 ms

In [20]:
#pd.set_option('display.max_rows', 600)
#pd.set_option('display.max_columns', 600)
p = ['202081800','201767805','202082626','202083756','301000116',
     '201065382','301000066','202081172','201668474','202080562',
     '200665695','200165209','199865718','202082055','202096931',
     '202080174','201440668','200665141','200966325','200965483'
    ]
#for i in p:
#    display(oecddf[oecddf['ProjectNumber']==i])

oecddf[oecddf['ProjectNumber'].isin(p)].to_csv('projects_details.csv')